const desiredConfig = {
    iobEnabled: true,
    iobMonitoringEnabled: true,
    iobAutoImageUpdate: false,
    image: 'influxdb:2',
    name: 'iobroker_influxdb.0',
    ports: [
        {
            hostPort: 8086,
            containerPort: 8086,
            hostIP: '127.0.0.1',
        },
    ],
    mounts: [
        {
            source: '/opt/iobroker/iobroker-data/influxdb.0/data',
            target: '/var/lib/influxdb2',
            type: 'bind',
        },
        {
            source: '/opt/iobroker/iobroker-data/influxdb.0/config',
            target: '/etc/influxdb2',
            type: 'bind',
        },
    ],
    environment: {
        DOCKER_INFLUXDB_INIT_USERNAME: 'iobroker',
        DOCKER_INFLUXDB_INIT_PASSWORD: 'iobroker',
        DOCKER_INFLUXDB_INIT_BUCKET: 'iobroker',
        DOCKER_INFLUXDB_INIT_ORG: 'iobroker',
        DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 'aW9icm9rZXI4NjY0NTYzODU0NjU2NTY1MjY1Ng==',
    },
};

const existingConfig = {
    image: 'influxdb:2',
    name: 'iobroker_influxdb.0',
    command: ['influxd'],
    entrypoint: ['/entrypoint.sh'],
    user: '',
    workdir: '',
    hostname: 'a57b18ae7ca1',
    domainname: '',
    macAddress: '',
    environment: {
        DOCKER_INFLUXDB_INIT_USERNAME: 'iobroker',
        DOCKER_INFLUXDB_INIT_PASSWORD: 'iobroker',
        DOCKER_INFLUXDB_INIT_BUCKET: 'iobroker',
        DOCKER_INFLUXDB_INIT_ORG: 'iobroker',
        DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 'aW9icm9rZXI4NjY0NTYzODU0NjU2NTY1MjY1Ng==',
        DOCKER_INFLUXDB_INIT_MODE: 'setup',
        PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        GOSU_VER: '1.16',
        INFLUXDB_VERSION: '2.7.12',
        INFLUX_CLI_VERSION: '2.7.5',
        INFLUX_CONFIGS_PATH: '/etc/influxdb2/influx-configs',
        INFLUXD_INIT_PORT: '9999',
        INFLUXD_INIT_PING_ATTEMPTS: '600',
        DOCKER_INFLUXDB_INIT_CLI_CONFIG_NAME: 'default',
    },
    labels: {},
    tty: false,
    stdinOpen: false,
    attachStdin: false,
    attachStdout: false,
    attachStderr: false,
    openStdin: false,
    publishAllPorts: false,
    ports: [
        {
            containerPort: '8086',
            protocol: 'tcp',
            hostPort: '8086',
            hostIP: '127.0.0.1',
        },
    ],
    mounts: [
        {
            type: 'bind',
            source: '/opt/iobroker/iobroker-data/influxdb.0/config',
            target: '/etc/influxdb2',
            readOnly: true,
        },
        {
            type: 'bind',
            source: '/opt/iobroker/iobroker-data/influxdb.0/data',
            target: '/var/lib/influxdb2',
            readOnly: true,
        },
    ],
    volumes: ['/etc/influxdb2', '/var/lib/influxdb2'],
    dns: {
        servers: [],
        search: [],
        options: [],
    },
    networkMode: 'bridge',
    networks: [
        {
            name: 'bridge',
            ipv4Address: '',
            ipv6Address: '',
        },
    ],
    restart: {
        policy: 'no',
        maxRetries: 0,
    },
    resources: {
        cpuShares: 0,
        cpuQuota: 0,
        cpuPeriod: 0,
        cpusetCpus: '',
        memory: 0,
        memorySwap: 0,
        memoryReservation: 0,
        shmSize: 67108864,
        readOnlyRootFilesystem: false,
    },
    logging: {
        driver: 'json-file',
        options: {},
    },
    security: {
        privileged: false,
        usernsMode: '',
        ipc: 'private',
        pid: '',
        apparmor: '',
    },
    stop: {},
    readOnly: false,
};
